pgdi/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app/', include('pgdiapp.urls')),
    url(r'^$', RedirectView.as_view(url='/app/')),
]

pgdiapp/urls.py
from django.conf.urls import url
from pgdiapp.views import *

from . import views

# URLs

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^error$', views.error, name='error'),
	url(r'^regmod$', views.regmod, name='regmod'),
	url(r'^funmod$', views.funmod, name='funmod'),
	url(r'^registro$', views.registro, name='registro'),
	url(r'^regreso$', views.regreso, name='regreso'),
	url(r'^login$', views.login_view, name='login_view'),
	url(r'^logout$', views.logout_view, name='logout_view'),
	url(r'^logout_redirect$', views.logoutr, name='logoutr'),
	url(r'^chpasswd$', views.chpasswd, name='chpasswd'),
	url(r'^chpasswd_redirect$', views.chpasswdr, name='chpasswdr'),
	url(r'^alumnos$', views.alumnos, name='alumnos'),
	url(r'^pendientes$', views.pendientes, name='pendientes'),
	url(r'^noencontrado$', views.noencontrado, name='noencontrado'),
	url(r'^formatonovalido$', views.formatonovalido, name='formatonovalido'),
	url(r'^descarte/(?P<grado>[A-Z]+)/(?P<usuario>[a-zA-Z0-9]+)$', views.descarte, name='descarte'),
	url(r'^confirmar_descarte/(?P<grado>[A-Z]+)/(?P<usuario>[a-zA-Z0-9]+)$', views.confirmar_descarte, name='confirmar_descarte'),
	url(r'^perfil/(?P<grado>[A-Z]+)/(?P<usuario>[a-zA-Z0-9]+)$', views.perfil, name='perfil'),
	url(r'^perfil/(?P<grado>[A-Z]+)/(?P<usuario>[a-zA-Z0-9]+)/editar$', views.editar, name='editar'),
	url(r'^perfil/(?P<grado>[A-Z]+)/(?P<usuario>[a-zA-Z0-9]+)/foto$', views.subir_foto, name='subir_foto'),
	url(r'^perfil/(?P<grado>[A-Z]+)/(?P<usuario>[a-zA-Z0-9]+)/respuestas$', views.respuestas, name='respuestas'),
	url(r'^alta/(?P<grado>[A-Z]+)/(?P<usuario>[a-zA-Z0-9]+)$', views.alta, name='alta'),
	url(r'^baja/(?P<grado>[A-Z]+)/(?P<usuario>[a-zA-Z0-9]+)$', views.baja, name='baja'),
	url(r'^confirmar_baja/(?P<grado>[A-Z]+)/(?P<usuario>[a-zA-Z0-9]+)$', views.confirmar_baja, name='confirmar_baja'),
	url(r'^cuestionario/(?P<user_name>[a-zA-Z0-9]+)$', views.cuestionario, name='cuestionario'),
]

pgdiapp/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models
from django.core.validators import RegexValidator, MinValueValidator, MaxValueValidator, MaxLengthValidator, MinLengthValidator
from localflavor.es.forms import ESIdentityCardNumberField

# Modelos

class Taller(models.Model):
	cod = models.CharField(max_length=5, unique=True)
	numero = models.IntegerField(validators=[MinValueValidator(1),MaxValueValidator(4)])
	info = models.TextField(default=None, blank=True, null=True)
	def __str__(self):
		return str(self.cod)
	class Meta:
		ordering = ["cod"]
		verbose_name_plural = "Talleres"

class Grado(models.Model):
	cod = models.CharField(max_length=5, unique=True)
	nombre = models.CharField(max_length=200, unique=True)
	nocturno = models.BooleanField(default=False)
	def __str__(self):
		return str(self.cod)
	class Meta:
		ordering = ["cod"]
		verbose_name_plural = "Grados"

class Clase(models.Model):
	grado = models.ForeignKey(Grado, on_delete=models.CASCADE)
	taller = models.ForeignKey(Taller, on_delete=models.CASCADE)
	curso = models.IntegerField(validators=[MinValueValidator(1),MaxValueValidator(2)])
	def __str__(self):
		return str(self.grado) + " - " + str(self.taller)
	class Meta:
		ordering = ["grado","taller"]
		unique_together = ('grado', 'taller')
		verbose_name_plural = "Clases"

class Perfil(models.Model):
	user = models.OneToOneField(User, unique=True, on_delete=models.CASCADE)
	grado = models.ForeignKey(Grado, blank=False, null=True, on_delete=models.CASCADE)
	passwd =  models.CharField(max_length=500, blank=False, null=True)
	dni_regex = RegexValidator(regex=r'^[0-9]{8}[a-zA-Z]{1}$')
	dni = models.CharField(max_length=9, validators=[dni_regex], unique=True, blank=False, null=True)
	nombre = models.CharField(validators=[MinLengthValidator(2),MaxLengthValidator(50)], max_length=50, blank=False, null=True)
	apellido1 = models.CharField(validators=[MinLengthValidator(2),MaxLengthValidator(50)], max_length=50, blank=False, null=True)
	apellido2 = models.CharField(validators=[MinLengthValidator(2),MaxLengthValidator(50)], max_length=50, blank=False, null=True)
	tel_regex = RegexValidator(regex=r'^\+?1?\d{9}$')
	telefono = models.CharField(max_length=9, validators=[tel_regex], blank=False, null=True)
	email = models.EmailField(blank=False, null=True)
	fecha_nac = models.DateField(blank=False, null=True)
	cp_regex = RegexValidator(regex=r'^[0-9]{5}$')
	cp = models.CharField(max_length=5, validators=[cp_regex], null=True)
	direccion = models.CharField(max_length=100, null=True)
	localidad = models.CharField(max_length=50, null=True)
	provincia = models.CharField(max_length=50, null=True)
	comunidad = models.CharField(max_length=50, null=True)
	pais = models.CharField(max_length=50, null=True)
	validado = models.BooleanField(default=False)
	def __str__(self):
		return str(self.user.username)
	class Meta:
		ordering = ["user"]
		verbose_name_plural = "Perfiles"

class Pregunta(models.Model):
	texto = models.CharField(max_length=300, null=False)
	def __str__(self):
		return str(self.texto)
	class Meta:
		ordering = ["texto"]
		verbose_name_plural = "Preguntas"

class Cuestionario(models.Model):
	grado = models.ForeignKey(Grado, on_delete=models.CASCADE)
	pregunta = models.ForeignKey(Pregunta, on_delete=models.CASCADE)
	def __str__(self):
		return str(self.grado)+": "+str(self.pregunta)
	class Meta:
		ordering = ["grado","pregunta"]
		unique_together = ('grado','pregunta')
		verbose_name_plural = "Cuestionarios"

class Respuesta(models.Model):
	alumno = models.ForeignKey(Perfil, on_delete=models.CASCADE)
	pregunta = models.ForeignKey(Pregunta, on_delete=models.CASCADE)
	texto = models.CharField(max_length=300, null=False)
	def __str__(self):
		return str(self.alumno)+" - "+str(self.pregunta)+": "+str(self.texto)
	class Meta:
		ordering = ["alumno","pregunta"]
		unique_together = ('alumno','pregunta')
		verbose_name_plural = "Respuestas"

class Grupo(models.Model):
	grado = models.ForeignKey(Grado, blank=False, null=False, on_delete=models.CASCADE)
	dn = models.CharField(max_length=200, null=False)
	desc =models.CharField(max_length=300, null=False)
	def __str__(self):
		return str(self.desc)
	class Meta:
		ordering = ["grado","desc"]
		unique_together = ('grado','dn')
		verbose_name_plural = "Grupos"

class Tipo(models.Model):
	clase = models.CharField(max_length=7, null=False, unique=True)
	def __str__(self):
		return str(self.clase)
	class Meta:
		ordering = ["clase"]
		verbose_name_plural = "Tipos"

class Portada(models.Model):
	grado = models.ForeignKey(Grado, blank=False, null=False, on_delete=models.CASCADE)
	tipo = models.ForeignKey(Tipo, blank=False, null=False, on_delete=models.CASCADE)
	mensaje = models.TextField(default=None, blank=True, null=True)
	visible = models.BooleanField(default=False)
	def __str__(self):
		return str(self.grado) + ": " + str(self.mensaje) + " (" + str(self.tipo) + ")"
	class Meta:
		ordering = ["grado"]
		verbose_name_plural = "Portadas"

class Mensaje(models.Model):
	cod = models.CharField(max_length=10, unique=True)
	asunto = models.CharField(max_length=100, null=False)
	cuerpo = models.TextField(default=None, null=False)
	def __str__(self):
		return str(self.cod)
	class Meta:
		ordering = ["cod"]
		verbose_name_plural = "Mensajes"

class Configuracion(models.Model):
	clave = models.CharField(max_length=100, unique=True)
	info = models.TextField(default=None, blank=True, null=True)
	valor = models.BooleanField(default=False)
	def __str__(self):
		return str(self.clave)
	class Meta:
		ordering = ["clave"]
		verbose_name_plural = "Configuraciones"

pgdiapp/forms.py
from django import forms
from .models import Perfil, Respuesta
from django.contrib.admin.widgets import AdminDateWidget 

class UserProfileForm(forms.ModelForm):
	class Meta:
		model = Perfil
		fields = ["dni","nombre","apellido1","apellido2","telefono","email","grado","fecha_nac","cp","direccion","localidad","provincia","comunidad","pais"]
		widgets = {
			'fecha_nac': forms.DateInput(attrs={'type': 'date'}),
		}

class UserProfileMiniForm(forms.ModelForm):
	class Meta:
		model = Perfil
		fields = ["telefono","email","cp","direccion","localidad","provincia","comunidad","pais"]


class RespuestaForm(forms.ModelForm):
	class Meta:
		model = Respuesta
		fields = ["alumno","pregunta","texto"]

class PhotoForm(forms.Form):
	photo = forms.ImageField()

pgdiapp/templates/pgdiapp/alumnos.html
{% extends "base.html" %}
{% load static %}
{% block content %}
	<script lang='javascript'>
		function check_all(obj) {
			//$('input[name=all_alumnos]').attr('checked', obj.checked);
			var l_alumnos = document.getElementsByName('all_alumnos');
			for (i = 0; i < l_alumnos.length; i++) l_alumnos[i].checked = obj.checked;
		}
	</script>
	<h2 class="sub-title">Listado de alumnos de {{ grado }}</h2>
	<div id="suit-center">
		{% if not user.is_authenticated or not user.is_staff %}
			<div class="alert alert-block alert-error"><h4><a href="{% url 'index' %}" class="text-error">No deberías estar aquí...</a></h4></div>
		{% else %}
			<div id="menu">
				{% if l_grados|length > 1 %}
				<form enctype="multipart/form-data" method="post">
					{% csrf_token %}
					<select onchange="document.getElementById('form_grado').click()" id="id_l_grado" name="l_grado" required="">
						{% for l_grado in l_grados %}
							<option value="{{ l_grado }}"{% if l_grado == grado %}selected="selected"{% endif %}>{{ l_grado }}</option>
						{% endfor %}
					</select>
					<button id="form_grado" class="btn btn-high btn-info oculto" type="submit">Mostrar listado</button>
				</form>
				{% endif %}
			</div>
			{% if alumnos|length %}
			<form enctype="multipart/form-data" method="post">
			{% csrf_token %}
				<input type="hidden" name="l_grado" value="{{ grado }}" />
				<div class="results">
					<table id="result_list" class="table table-striped table-bordered table-hover table-alumnos">
						<tr>
							<th><input class="alumno-check" type="checkbox" id="all" onclick="check_all(this);" /></th>
							<th>Nombre de usuario</th>
							<th>Nombre</th>
							<th>Apellidos</th>
							<th>DNI</th>
							<th>Fecha de nacimiento</th>
							<th>Correo electrónico</th>
							<th>Telefono</th>
							<th colspan="3"></th>
						</tr>
						{% for alumno in alumnos|dictsort:0 %}
							<tr>
								<td class="alumno-data"><input type="checkbox" name="all_alumnos" id="{{ alumno.0.1.uid.0 }}" value="{{ alumno.0.1.uid.0 }}" /></td>
								<td class="alumno-data"><a href="{% url 'perfil' grado alumno.0.1.uid.0 %}">{{ alumno.0.1.uid.0 }}</a></td>
								<td class="alumno-data">{{ alumno.0.1.givenName.0 }}</td>
								<td class="alumno-data">{{ alumno.0.1.sn.0 }}</td>
								<td class="alumno-data">{{ alumno.0.1.dni.0|slice:":8" }}-{{ alumno.0.1.dni.0|slice:"8:" }}</td>
								<td class="alumno-data">{{ alumno.0.1.fnac.0|slice:"6:8" }}/{{ alumno.0.1.fnac.0|slice:"4:6" }}/{{ alumno.0.1.fnac.0|slice:":4" }}</td>
								<td class="alumno-data">{{ alumno.0.1.mail.0 }}</td>
								<td class="alumno-data">{{ alumno.0.1.telephoneNumber.0 }}</td>
								<td class="alumno-button"><a href="{% url 'perfil' grado alumno.0.1.uid.0 %}"><img title="Ver perfil" class="pgdi-icon" src="{% static 'images/lens.png' %}"/></a></td>
								<td class="alumno-button"><a href="{% url 'respuestas' grado alumno.0.1.uid.0 %}"><img title="Evaluación inicial" class="pgdi-icon" src="{% static 'images/evaluacion_inicial.png' %}"/></a></td>
								<td class="alumno-button"><a href="{% url 'confirmar_baja' grado alumno.0.1.uid.0 %}"><img title="Dar de baja" class="pgdi-icon" src="{% static 'images/baja.png' %}"/></a></td>
							</tr>
						{% endfor %}
					</table>
				</div>
				<div class="actions">
					<select name="actions" required="">
						<option value="" selected="selected">---------</option>
						<option value="baja_selected">Dar de baja</option>
					</select>
					<button id="ok_button" type="submit" class="btn btn-high btn-info" title="Ejecutar la acción seleccionada">Confirmar</button>
				</div>
			</form>
			{% else %}
				<div class="alert alert-warn">No existen alumnos activos para este curso de <strong>{{ grado }}</strong></div>
			{% endif %}
			<div><button class="btn btn-high" onclick="location.href='{% url 'index' %}'">Volver</button></div>
		{% endif %}
	</div>
{% endblock %}

pgdiapp/templates/pgdiapp/edicion_perfil.html
{% extends "base.html" %}
{% load static %}
{% block content %}
	<h2 class="sub-title">Edición de perfil</h2>
	<body>
		<div id="suit-center">
		{% if user.is_authenticated and user.username == alumno.0.0.1.uid.0 or user.is_staff %}
			<fieldset class="module aligned first" >
				<form enctype="multipart/form-data" method="post">
					{% csrf_token %}
					{% if pform.errors %}
						<h4>Se han producido los siguientes errores:</h4>
							<div>
								{{ pform.errors }}
							</div>
						<br />
					{% endif %}
					<table class="table-overview registro">
						<tr>
							<td><label for="id_username">Nombre de<br>usuario:</label></td><td class="reg_input"><input disabled="disabled" type="text" value="{{ alumno.0.0.1.uid.0 }}"></td>
							<td><label for="id_email">e-Mail:</label></td><td class="reg_input"><input id="id_email" maxlength="254" name="email" required="" type="email" value="{{ alumno.0.0.1.mail.0 }}"></td>
							<td><label for="id_telefono">Teléfono:</label></td><td class="reg_input"><input id="id_telefono" maxlength="9" name="telefono" required="" type="text" value="{{ alumno.0.0.1.telephoneNumber.0 }}"></td>
						</tr>
						<tr>
							<td><label for="id_cp">Código<br>Postal:</label></td><td class="reg_input"><input id="id_cp" maxlength="5" name="cp" required="" type="text" value="{{ alumno.0.0.1.postalCode.0 }}"></td>
							<td><label for="id_direccion">Dirección:</label></td><td class="reg_input"><input id="id_direccion" maxlength="100" name="direccion" required="" type="text" value="{{ alumno.0.0.1.street.0 }}"></td>
							<td><label for="id_localidad">Localidad:</label></td><td class="reg_input"><input id="id_localidad" maxlength="50" name="localidad" required="" type="text" value="{{ alumno.0.0.1.l.0 }}"></td>
						</tr>
						<tr>
							<td><label for="id_provincia">Provincia:</label></td><td class="reg_input"><input id="id_provincia" maxlength="50" name="provincia" required="" type="text" value="{{ alumno.0.0.1.st.0 }}"></td>
							<td><label for="id_comunidad">Comunidad:</label></td><td class="reg_input"><input id="id_comunidad" maxlength="50" name="comunidad" required="" type="text" value="{{ alumno.0.0.1.c.0 }}"></td>
							<td><label for="id_pais">País:</label></td><td class="reg_input"><input id="id_pais" maxlength="50" name="pais" required="" type="text" value="{{ alumno.0.0.1.co.0 }}"></td>
						</tr>
					</table>
					<button class="btn btn-high btn-info" type="submit">Confirmar</button>
					<input type="button" class="btn btn-high" value="Volver" onclick="location.href='{% url 'perfil' grado alumno.0.0.1.uid.0 %}'">
				</form>
			</fieldset>
		{% else %}
			<div class="alert alert-block alert-error"><h4><a href="{% url 'index' %}" class="text-error">No deberías estar aquí...</a></h4></div>
		{% endif %}
		</div>
	</body>
{% endblock %}

pgdiapp/templates/pgdiapp/subir_foto.html
{% extends "base.html" %}
{% load static %}
{% block content %}
	<h2 class="sub-title">Subir foto de perfil</h2>
	<div id="suit-center">
		{% if user.is_authenticated and user.username == alumno or user.is_staff %}
			{% if form.errors %}
				<h4>Se han producido los siguientes errores:</h4>
					<div>
						{{ form.errors }}
					</div>
				<br />
			{% endif %}
			<br />
			<form enctype="multipart/form-data" method="post">
				{% csrf_token %}
				<div class="alert alert-info">Sólo se permiten imágenes en formato <strong>jpg</strong> y con un tamaño maximo de <strong>1MB</strong></div><hr />
				<label for="id_photo"></label>
				{{ form.photo }}
				<br /><br />
					<input type="submit" class="btn btn-high btn-info" value="Subir Foto" />
					<input type="button" value="Volver" onclick="location.href='{% url 'perfil' grado alumno %}'">
			</form>
		{% else %}
			<div class="alert alert-block alert-error"><h4><a href="{% url 'index' %}" class="text-error">No deberías estar aquí...</a></h4></div>
		{% endif %}
	</body>
{% endblock %}

pgdiapp/templates/pgdiapp/user_form.html
{% extends "base.html" %}
{% load static %}
{% block content %}
	<script lang='javascript'>
		function default_mod() {
			var grados = document.getElementById("id_grado").options
			for (i = 0; i < grados.length; i++) {
				if (grados[i].text == '{{ grado }}') document.getElementById("id_grado").selectedIndex = i;
			}
		}
	</script>
	<script src="//cdn.jsdelivr.net/webshim/1.14.5/polyfiller.js"></script>
	<script>
		jQuery.swap = function( elem, options, callback, args ) {
			var ret, name, old = {};
			// Remember the old values, and insert the new ones
			for ( name in options ) {
				old[ name ] = elem.style[ name ];
				elem.style[ name ] = options[ name ];
			}
			ret = callback.apply( elem, args || [] );
			// Revert the old values
			for ( name in options ) {
				elem.style[ name ] = old[ name ];
			}
			return ret;
		};
		webshims.setOptions('forms-ext', {
			types: 'date', 
			"date": {
					"startView": 0
				}
			}
		);
		webshims.polyfill('forms forms-ext');
	</script>
	<script type="text/javascript" src="https://maps.google.com/maps/api/js?key=AIzaSyAHJXeUeWW-dv3IMxOZVVuLRcMt62hO6Eg"></script>
	<script lang='javascript'>
	var map, geocoder;
	function inicio() {
	var latlng = new google.maps.LatLng(36.500648, -6.272241);
	var mapOptions = {
	  zoom: 10,
	  center: latlng,
	  mapTypeId: google.maps.MapTypeId.ROADMAP
	};
	map = new google.maps.Map(document.getElementById('mapa'), mapOptions);
	geocoder = new google.maps.Geocoder();
	};
	function codeAddress() {
	document.getElementById('dir_ok').innerHTML = "<strong>❋ Confirme o corrija los datos ↴</strong>"
	//document.getElementById('addr1').style.display = "";
	//document.getElementById('addr2').style.display = "";
	//document.getElementById('addr3').style.display = "";
	var address = document.getElementById('address').value;
	geocoder.geocode({
	  'address': address
		// 'latLng': latlng si lo que queremos ejecutar en geocodificación inversa
	}, function(results, status) {
	  if (status == google.maps.GeocoderStatus.OK) {
		//document.getElementById('x').innerHTML = results[0].geometry.location.lat().toFixed(6);
		//document.getElementById('y').innerHTML = results[0].geometry.location.lng().toFixed(6);
		map.setCenter(results[0].geometry.location);
		document.getElementById('address').value = results[0].formatted_address;
		var marker = new google.maps.Marker({
		  map: map,
		  position: results[0].geometry.location
		});
			var route = ""
			var street_number = ""
			for(var j=0;j < results[0].address_components.length; j++){
				for(var k=0; k < results[0].address_components[j].types.length; k++){
					if(results[0].address_components[j].types[k] == "postal_code"){
						zipcode = results[0].address_components[j].short_name;
						document.getElementById('id_cp').value = zipcode;
					}
					if(results[0].address_components[j].types[k] == "route"){
						route = results[0].address_components[j].short_name;
					}
					if(results[0].address_components[j].types[k] == "street_number"){
						street_number = results[0].address_components[j].short_name;
					}
					if(results[0].address_components[j].types[k] == "locality"){
						locality = results[0].address_components[j].short_name;
						document.getElementById('id_localidad').value = locality;
					}
					if(results[0].address_components[j].types[k] == "administrative_area_level_1"){
						administrative_area_level_1 = results[0].address_components[j].long_name;
						document.getElementById('id_comunidad').value = administrative_area_level_1;
					}
					if(results[0].address_components[j].types[k] == "administrative_area_level_2"){
						administrative_area_level_2 = results[0].address_components[j].long_name;
						document.getElementById('id_provincia').value = administrative_area_level_2;
					}
					if(results[0].address_components[j].types[k] == "country"){
						country = results[0].address_components[j].long_name;
						if (country == "Spain") country = 'España';
						document.getElementById('id_pais').value = country;
					}
				}
			}
			document.getElementById('id_direccion').value = route + ", " + street_number;
		infowindow = new google.maps.InfoWindow({
		  content: results[0].formatted_address + '<br> Latitud: ' + results[0].geometry.location.lat().toFixed(6) + '<br> Longitud: ' + results[0].geometry.location.lng().toFixed(6)
		});
		infowindow.open(map, marker)
	  }
	  // Se detallan los diferentes tipos de error
	  else {
		alert('Geocode no tuvo éxito por la siguiente razón: ' + status)
	  }
	})
	};
	google.maps.event.addDomListener(window, 'load', inicio);
	</script>
	
	<h2 class="sub-title">Presentación</h2>
	<body onload="default_mod()">
		<div id="suit-center">
			{% if user.is_authenticated or not openrg %}
				<div class="alert alert-block alert-error"><h4><a href="{% url 'index' %}" class="text-error">No deberías estar aquí...</a></h4></div>
			{% else %}
			<div class="alert alert-info">
				Parece que estas accediendo desde la ip <strong>{{ ip }}</strong>. 
				{% if grado != 'desconocido' %}Seguramente seas alumno de <strong>{{ grado }}</strong>{% endif %}. 
				Si eres un antiguo alumno haz click [ <a href="{% url 'regreso' %}"><strong>AQUÍ</strong></a> ]
			</div><hr />
			<fieldset class="module aligned first" >
				<form enctype="multipart/form-data" method="post">
					{% csrf_token %}
					{% if uform.errors or pform.errors %}
						<h4>Se han producido los siguientes errores:</h4>
							<div>
								{{ uform.errors }}
								{{ pform.errors }}
							</div>
						<br />
					{% endif %}
					<table class="table-overview registro">
						<tr>
							{% if freeun %}
							<td colspan="2" class="reg_input"><strong>❋ Puede elegir el nombre de usuario deseado.</strong></td>
							<td><label for="id_username">Nombre de<br>usuario:</label></td><td class="reg_input">{{ uform.username }}</td>
							{% else %}
							<td colspan="2" class="reg_input"><strong>❋ No es posible elegir el nombre de usuario.</strong></td>
							<input id="username" type="hidden" name="username" value="dummy">
							<td><label for="id_username">Nombre de<br>usuario:</label></td><td class="reg_input"><input disabled="disabled" type="text"></td>
							{% endif %}
							<td><label for="id_dni">DNI:</label></td><td class="reg_input">{{ pform.dni }}</td>
						</tr>
						<tr>
							<td>{{ pform.nombre.label_tag }}</td><td class="reg_input">{{ pform.nombre }}</td>
							<td><label for="id_apellido1">1º Apellido:</label></td><td class="reg_input">{{ pform.apellido1 }}</td>
							<td><label for="id_apellido2">2º Apellido:</label></td><td class="reg_input">{{ pform.apellido2 }}</td>
						</tr>
						<tr>
							<td><label for="id_grado">Grado:</label></td><td class="reg_input">{{ pform.grado }}</td>
							<td><label for="id_email">e-Mail:</label></td><td class="reg_input">{{ pform.email }}</td>
							<td><label for="id_telefono">Teléfono:</label></td><td class="reg_input">{{ pform.telefono }}</td>
						</tr>
						<tr>
							<td><label for="id_fecha_nac">Fecha de<br>Nacimiento:</label></td><td class="reg_input"><input id="id_fecha_nac" placeholder="dd/mm/yyyy" name="fecha_nac" required="" type="date"></td>
							<td><label for="id_contraseña1">Contraseña:</label></td><td class="reg_input">{{ uform.password1 }}</td>
							<td><label for="id_contraseña2">Contraseña:</label></td><td class="reg_input">{{ uform.password2 }}</td>
						</tr>
						<tr>
							<td><label for="id_address">Dirección<br>completa:</label></td>
							<td colspan="3" class="reg_input"><input id="address" type="text" maxlength="100" value="" placeholder="c/ Conil de la Frontera, 3, 11011 Cádiz, Spain" /></td>
							<td><input id="localizar" type="button" class="button" value="Localizar" onclick="codeAddress()"></td><td class="reg_input"><div id="dir_ok"><strong>⇦ Pulse "Localizar"</strong></div></td>
						</tr>
						<tr id="addr1" style="display:;">
							<td><label for="id_cp">Código<br>Postal:</label></td><td class="reg_input">{{ pform.cp }}</td>
							<td><label for="id_direccion">Dirección:</label></td><td class="reg_input">{{ pform.direccion }}</td>
							<td>{{ pform.localidad.label_tag }}</td><td class="reg_input">{{ pform.localidad }}</td>
						</tr>
						<tr id="addr2" style="display:;">
							<td>{{ pform.provincia.label_tag }}</td><td class="reg_input">{{ pform.provincia }}</td>
							<td>{{ pform.comunidad.label_tag }}</td><td class="reg_input">{{ pform.comunidad }}</td>
							<td><label for="id_pais">País:</label></td><td class="reg_input">{{ pform.pais }}</td>
						</tr>
						<tr id="addr3" style="display:;">
							<td colspan="6"><div id="mapa"></div></td>
						</tr>
					</table>
					<br />
					<button class="btn btn-high btn-info" type="submit">Confirmar</button>
					<button class="btn btn-high" onclick="location.href='{% url 'index' %}'">Volver</button>
				</form>
			</fieldset>
			{% endif %}
		</div>
	</body>
{% endblock %}